name: jekyll-site-from-scratch
url: https://noshadchaudhrywebdev1.github.io/jekyll-site-from-scratch
baseurl: /jekyll-site-from-scratch
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - github-pages
